#!/bin/bash
# Simple helper for the OCF ZFS scripts which performs actions on the
# imported/exported pool. Place this script in
# ${OCF_ROOT}/lib/heartbeat/helpers/


case "$1" in
	pre-import)
		exit 0;;
	post-import)
		exit 0;;
	pre-export)
		exit 0;;
	post-export)
		exit 0;;
	*)	echo "Usage: $0" \
		     "[pre-import|post-import|pre-export|post-export]" \
		     "<poolname>" >&2
		exit 1;;
esac